import { CitiesResponse } from './app/weather';

export const WeatherData: CitiesResponse = {
  cities: [
    {
      id: 1,
      city: 'Bengaluru',
      temperature: '20',
      description: 'Clear',
      sunrise: '06:44',
      sunset: '17:59',
      additionalDetails: {
        humidity: '63%',
        windForce: '3',
        uvIndex: '5',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '14',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '01:00',
          temperature: '13',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '02:00',
          temperature: '13',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '03:00',
          temperature: '12',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '04:00',
          temperature: '12',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '05:00',
          temperature: '11',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '06:00',
          temperature: '12',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '07:00',
          temperature: '14',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '08:00',
          temperature: '16',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '09:00',
          temperature: '18',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '10:00',
          temperature: '19',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '11:00',
          temperature: '21',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '12:00',
          temperature: '22',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '13:00',
          temperature: '23',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '14:00',
          temperature: '24',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '15:00',
          temperature: '25',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '16:00',
          temperature: '26',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '17:00',
          temperature: '25',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '18:00',
          temperature: '24',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '19:00',
          temperature: '23',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '20:00',
          temperature: '22',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '21:00',
          temperature: '21',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '22:00',
          temperature: '20',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '23:00',
          temperature: '19',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
      ],
    },
    {
      id: 2,
      city: 'New York',
      temperature: '18',
      description: 'Cloudy',
      sunrise: '06:30',
      sunset: '18:45',
      additionalDetails: {
        humidity: '70%',
        windForce: '4',
        uvIndex: '3',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '16',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '01:00',
          temperature: '15',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '02:00',
          temperature: '15',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '03:00',
          temperature: '14',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '04:00',
          temperature: '13',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '05:00',
          temperature: '13',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '06:00',
          temperature: '14',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '07:00',
          temperature: '15',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '08:00',
          temperature: '17',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '09:00',
          temperature: '18',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '10:00',
          temperature: '19',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '11:00',
          temperature: '20',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '12:00',
          temperature: '21',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '13:00',
          temperature: '22',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '14:00',
          temperature: '23',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '15:00',
          temperature: '24',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '16:00',
          temperature: '23',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '17:00',
          temperature: '22',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '18:00',
          temperature: '21',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '19:00',
          temperature: '20',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '20:00',
          temperature: '19',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '21:00',
          temperature: '18',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '22:00',
          temperature: '17',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '23:00',
          temperature: '16',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
      ],
    },
    {
      id: 3,
      city: 'Los Angeles',
      temperature: '24',
      description: 'Sunny',
      sunrise: '06:15',
      sunset: '19:00',
      additionalDetails: {
        humidity: '50%',
        windForce: '2',
        uvIndex: '7',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '20',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '01:00',
          temperature: '19',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '02:00',
          temperature: '18',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '03:00',
          temperature: '17',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '04:00',
          temperature: '16',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '05:00',
          temperature: '16',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '06:00',
          temperature: '17',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '07:00',
          temperature: '18',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '08:00',
          temperature: '20',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '09:00',
          temperature: '22',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '10:00',
          temperature: '24',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '11:00',
          temperature: '26',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '12:00',
          temperature: '27',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '13:00',
          temperature: '28',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '14:00',
          temperature: '29',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '15:00',
          temperature: '30',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '16:00',
          temperature: '29',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '17:00',
          temperature: '28',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '18:00',
          temperature: '26',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '19:00',
          temperature: '24',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '20:00',
          temperature: '22',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '21:00',
          temperature: '21',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '22:00',
          temperature: '20',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '23:00',
          temperature: '19',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
      ],
    },
    {
      id: 4,
      city: 'London',
      temperature: '16',
      description: 'Rain',
      sunrise: '07:00',
      sunset: '18:30',
      additionalDetails: {
        humidity: '85%',
        windForce: '5',
        uvIndex: '2',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '12',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '01:00',
          temperature: '11',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '02:00',
          temperature: '11',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '03:00',
          temperature: '10',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '04:00',
          temperature: '10',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '05:00',
          temperature: '10',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '06:00',
          temperature: '11',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '07:00',
          temperature: '12',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '08:00',
          temperature: '13',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '09:00',
          temperature: '14',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '10:00',
          temperature: '15',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '11:00',
          temperature: '16',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '12:00',
          temperature: '17',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '13:00',
          temperature: '18',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '14:00',
          temperature: '19',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '15:00',
          temperature: '20',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '16:00',
          temperature: '19',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '17:00',
          temperature: '18',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '18:00',
          temperature: '17',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '19:00',
          temperature: '16',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '20:00',
          temperature: '15',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '21:00',
          temperature: '14',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '22:00',
          temperature: '13',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '23:00',
          temperature: '12',
          condition: 'Rain',
          icon: 'rain.png',
        },
      ],
    },
    {
      id: 5,
      city: 'Tokyo',
      temperature: '22',
      description: 'Partly Cloudy',
      sunrise: '05:50',
      sunset: '18:20',
      additionalDetails: {
        humidity: '60%',
        windForce: '4',
        uvIndex: '6',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '19',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '01:00',
          temperature: '18',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '02:00',
          temperature: '18',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '03:00',
          temperature: '17',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '04:00',
          temperature: '16',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '05:00',
          temperature: '16',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '06:00',
          temperature: '17',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '07:00',
          temperature: '18',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '08:00',
          temperature: '20',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '09:00',
          temperature: '22',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '10:00',
          temperature: '24',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '11:00',
          temperature: '25',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '12:00',
          temperature: '26',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '13:00',
          temperature: '27',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '14:00',
          temperature: '28',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '15:00',
          temperature: '29',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '16:00',
          temperature: '28',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '17:00',
          temperature: '27',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '18:00',
          temperature: '26',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '19:00',
          temperature: '24',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '20:00',
          temperature: '23',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '21:00',
          temperature: '22',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '22:00',
          temperature: '21',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '23:00',
          temperature: '20',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
      ],
    },
    {
      id: 6,
      city: 'Paris',
      temperature: '18',
      description: 'Partly Cloudy',
      sunrise: '06:50',
      sunset: '18:40',
      additionalDetails: {
        humidity: '68%',
        windForce: '3',
        uvIndex: '4',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '15',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '01:00',
          temperature: '14',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '02:00',
          temperature: '13',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '03:00',
          temperature: '13',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '04:00',
          temperature: '12',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '05:00',
          temperature: '12',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '06:00',
          temperature: '13',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '07:00',
          temperature: '14',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '08:00',
          temperature: '16',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '09:00',
          temperature: '17',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '10:00',
          temperature: '18',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '11:00',
          temperature: '19',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '12:00',
          temperature: '20',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '13:00',
          temperature: '21',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '14:00',
          temperature: '22',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '15:00',
          temperature: '23',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '16:00',
          temperature: '22',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '17:00',
          temperature: '21',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '18:00',
          temperature: '20',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '19:00',
          temperature: '19',
          condition: 'Clear',
          icon: 'clear_night.png',
        },
        {
          time: '20:00',
          temperature: '18',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '21:00',
          temperature: '17',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '22:00',
          temperature: '16',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '23:00',
          temperature: '15',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
      ],
    },
    {
      id: 7,
      city: 'Sydney',
      temperature: '25',
      description: 'Sunny',
      sunrise: '05:45',
      sunset: '19:15',
      additionalDetails: {
        humidity: '55%',
        windForce: '3',
        uvIndex: '8',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '21',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '01:00',
          temperature: '20',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '02:00',
          temperature: '19',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '03:00',
          temperature: '18',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '04:00',
          temperature: '18',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '05:00',
          temperature: '19',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '06:00',
          temperature: '20',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '07:00',
          temperature: '22',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '08:00',
          temperature: '24',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '09:00',
          temperature: '26',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '10:00',
          temperature: '27',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '11:00',
          temperature: '28',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '12:00',
          temperature: '29',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '13:00',
          temperature: '30',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '14:00',
          temperature: '31',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '15:00',
          temperature: '32',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '16:00',
          temperature: '31',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '17:00',
          temperature: '30',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '18:00',
          temperature: '28',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '19:00',
          temperature: '26',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '20:00',
          temperature: '24',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '21:00',
          temperature: '22',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '22:00',
          temperature: '21',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '23:00',
          temperature: '20',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
      ],
    },
    {
      id: 8,
      city: 'Dubai',
      temperature: '35',
      description: 'Sunny',
      sunrise: '06:00',
      sunset: '18:30',
      additionalDetails: {
        humidity: '40%',
        windForce: '2',
        uvIndex: '9',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '30',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '01:00',
          temperature: '29',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '02:00',
          temperature: '28',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '03:00',
          temperature: '27',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '04:00',
          temperature: '26',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '05:00',
          temperature: '26',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '06:00',
          temperature: '27',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '07:00',
          temperature: '29',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '08:00',
          temperature: '32',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '09:00',
          temperature: '34',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '10:00',
          temperature: '35',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '11:00',
          temperature: '36',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '12:00',
          temperature: '37',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '13:00',
          temperature: '38',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '14:00',
          temperature: '39',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '15:00',
          temperature: '40',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '16:00',
          temperature: '39',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '17:00',
          temperature: '38',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '18:00',
          temperature: '36',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '19:00',
          temperature: '34',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '20:00',
          temperature: '32',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '21:00',
          temperature: '30',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '22:00',
          temperature: '29',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '23:00',
          temperature: '28',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
      ],
    },
    {
      id: 9,
      city: 'Moscow',
      temperature: '10',
      description: 'Cloudy',
      sunrise: '07:30',
      sunset: '17:45',
      additionalDetails: {
        humidity: '75%',
        windForce: '5',
        uvIndex: '2',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '8',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '01:00',
          temperature: '7',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '02:00',
          temperature: '7',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '03:00',
          temperature: '6',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '04:00',
          temperature: '6',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '05:00',
          temperature: '5',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '06:00',
          temperature: '6',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '07:00',
          temperature: '7',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '08:00',
          temperature: '8',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '09:00',
          temperature: '9',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '10:00',
          temperature: '10',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '11:00',
          temperature: '11',
          condition: 'Rainy Day',
          icon: 'rainy_day.png',
        },
        {
          time: '12:00',
          temperature: '12',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '13:00',
          temperature: '13',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '14:00',
          temperature: '14',
          condition: 'Rain',
          icon: 'rain.png',
        },
        {
          time: '15:00',
          temperature: '13',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '16:00',
          temperature: '12',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '17:00',
          temperature: '11',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '18:00',
          temperature: '10',
          condition: 'Cloudy',
          icon: 'cloudy.png',
        },
        {
          time: '19:00',
          temperature: '9',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '20:00',
          temperature: '8',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '21:00',
          temperature: '7',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '22:00',
          temperature: '6',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
        {
          time: '23:00',
          temperature: '5',
          condition: 'Cloudy Night',
          icon: 'cloudy_night.png',
        },
      ],
    },
    {
      id: 10,
      city: 'Rio de Janeiro',
      temperature: '28',
      description: 'Partly Cloudy',
      sunrise: '05:30',
      sunset: '18:15',
      additionalDetails: {
        humidity: '70%',
        windForce: '3',
        uvIndex: '7',
      },
      hourlyForecast: [
        {
          time: '00:00',
          temperature: '24',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '01:00',
          temperature: '23',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '02:00',
          temperature: '22',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '03:00',
          temperature: '21',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '04:00',
          temperature: '20',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '05:00',
          temperature: '20',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '06:00',
          temperature: '22',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '07:00',
          temperature: '24',
          condition: 'Partly Cloudy',
          icon: 'partly_cloudy.png',
        },
        {
          time: '08:00',
          temperature: '26',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '09:00',
          temperature: '28',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '10:00',
          temperature: '30',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '11:00',
          temperature: '32',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '12:00',
          temperature: '33',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '13:00',
          temperature: '34',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '14:00',
          temperature: '35',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '15:00',
          temperature: '34',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '16:00',
          temperature: '33',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '17:00',
          temperature: '31',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '18:00',
          temperature: '29',
          condition: 'Sunny',
          icon: 'sunny.png',
        },
        {
          time: '19:00',
          temperature: '27',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '20:00',
          temperature: '26',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '21:00',
          temperature: '25',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '22:00',
          temperature: '24',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
        {
          time: '23:00',
          temperature: '23',
          condition: 'Clear Night',
          icon: 'clear_night.png',
        },
      ],
    },
  ],
};
